on-cable is now capable of executing hooks on attach or detach

diff --git a/on-cable b/on-cable
--- a/on-cable
+++ b/on-cable
@@ -6,21 +6,37 @@ safe_source () { [[ ! -z ${1:-} ]] && source $1; _dir="$(cd "$(dirname "${BASH_S
 safe_source $_sdir/lib/all.sh
 set +e # do not exit on error
 
-hook=$1
-if [[ -x $PWD/$hook ]]; then
+edge=${1:-} # "attach" or "detach"
+if [[ -z $edge ]]; then
+    echo "First parameter should be edge (attach or detach)"
+    exit 1
+fi
+
+hook=${2:-}
+if [[ -z $hook ]]; then
+    echo "Hook script is required."
+    exit 1
+fi
+if [[ -f $PWD/$hook ]]; then
     hook=$PWD/$hook
-elif [[ -x $_sdir/$hook ]]; then
+elif [[ -f $_sdir/$hook ]]; then
     hook=$_sdir/$hook
 elif `hash $hook`; then
-    true
+    hook=`which $hook`
 else
-    echo "Hook script is required."
+    echo "Hook script can not be found."
+    exit 1
+fi
+
+if [[ ! -x $hook ]]; then
+    echo "Hook script should be executable."
     exit 1
 fi
 
 [[ $(whoami) = "root" ]] || { sudo $0 $*; exit 0; }
 
 # re-align rest of the parameters
+shift
 shift
 
 echo "Hook script will be used: $hook $*"
@@ -29,18 +45,27 @@ echo "Hook script will be used: $hook $*"
 echo_green "Starting daemon..."
 connected0=true
 connected=false
-check_period=5s
+check_period=2s
 while true; do
 	if ! is_cable_plugged eth0; then
         if [[ $connected0 = true ]] && [[ $connected = false ]]; then
-            echo_red "Cable is detached, triggering $(basename $hook)"
-            $hook $*
+            if [[ "$edge" == "detach" ]]; then
+                echo_red "Cable is detached, triggering $(basename $hook)"
+                $hook $*
+            else
+                echo_red "Cable is detached."
+            fi
         fi
         connected0=$connected
         connected=false
 	else
     	if [[ $connected0 = false ]] && [[ $connected = true ]]; then
-            echo_green "Cable is attached."
+            if [[ "$edge" == "attach" ]]; then
+                echo_green "Cable is attached, triggering $(basename $hook)"
+                $hook $*
+            else
+                echo_green "Cable is attached."
+            fi
         fi
         connected0=$connected
         connected=true
